### ISSUE TITLE
Crash when decrypt if the encrypted string has '\n' in the end.

### ISSUE THREAD

**Issue by atjason** [SwiftyBeaver/AES256CBC#7]
In some case, the encrypted may have '\n' in the end. If try to decrypt, AES265CBC will crash here:

```swift

    fileprivate class func aesDecrypt(_ str: String, key: String, iv: String) throws -> String {
        let keyData = key.data(using: String.Encoding.utf8)!
        let ivData = iv.data(using: String.Encoding.utf8)!
        //let data = Data(base64Encoded: str, options: NSData.Base64DecodingOptions(rawValue: 0))!
        let data = Data(base64Encoded: str)!
```

**Comment by skreutzberger** [comment]
Can you please give a test case or example? I am asking because SwiftyBeaver is encrypting with `\n` all the time and it works.

**Comment by atjason** [comment]
@skreutzberger I didn't mean '\n' wasn't encrypted. 

The case I met was, the encrypted string (e..g, "abcd" was saved in file. When read it from the file, '\n' was appended to end of the encrypted string by mistake. In this case when try to decrypt the string of "abcd\n", AES256CBC crashes.

I didn't append a project as I thought it's easy to reproduce:

- Encrypt a string.
- Manually append '\n' in end of the encrypted string.
- Try to decrypt it.

**Comment by skreutzberger** [comment]
alright, I will check it out. Thanks for reporting!

**Comment by skreutzberger** [comment]
Hi, sorry for the delay. I tried as hard as I can but I could not reproduce the issue. Neither under Linux nor under Mac. In general, you should not change the encrypted string because any change will make decrypting impossible. Today a new version of AES256CBC is released which is in general more fault-tolerant (and also works under Swift 3.1). So maybe the mentioned issue was already fixed.
